/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context as ContextModule } from "./api/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CancellationsListRelationFilter: { // input type
    every?: NexusGenInputs['CancellationsWhereInput'] | null; // CancellationsWhereInput
    none?: NexusGenInputs['CancellationsWhereInput'] | null; // CancellationsWhereInput
    some?: NexusGenInputs['CancellationsWhereInput'] | null; // CancellationsWhereInput
  }
  CancellationsWhereInput: { // input type
    AND?: NexusGenInputs['CancellationsWhereInput'][] | null; // [CancellationsWhereInput!]
    NOT?: NexusGenInputs['CancellationsWhereInput'][] | null; // [CancellationsWhereInput!]
    OR?: NexusGenInputs['CancellationsWhereInput'][] | null; // [CancellationsWhereInput!]
    course?: NexusGenInputs['CoursesWhereInput'] | null; // CoursesWhereInput
    course_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    date?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    deleted_at?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  ChildrenListRelationFilter: { // input type
    every?: NexusGenInputs['ChildrenWhereInput'] | null; // ChildrenWhereInput
    none?: NexusGenInputs['ChildrenWhereInput'] | null; // ChildrenWhereInput
    some?: NexusGenInputs['ChildrenWhereInput'] | null; // ChildrenWhereInput
  }
  ChildrenWhereInput: { // input type
    AND?: NexusGenInputs['ChildrenWhereInput'][] | null; // [ChildrenWhereInput!]
    NOT?: NexusGenInputs['ChildrenWhereInput'][] | null; // [ChildrenWhereInput!]
    OR?: NexusGenInputs['ChildrenWhereInput'][] | null; // [ChildrenWhereInput!]
    birth_date?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    courses?: NexusGenInputs['CoursesListRelationFilter'] | null; // CoursesListRelationFilter
    first_name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    tutor?: NexusGenInputs['UsersWhereInput'] | null; // UsersWhereInput
    tutor_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  CoursesListRelationFilter: { // input type
    every?: NexusGenInputs['CoursesWhereInput'] | null; // CoursesWhereInput
    none?: NexusGenInputs['CoursesWhereInput'] | null; // CoursesWhereInput
    some?: NexusGenInputs['CoursesWhereInput'] | null; // CoursesWhereInput
  }
  CoursesWhereInput: { // input type
    AND?: NexusGenInputs['CoursesWhereInput'][] | null; // [CoursesWhereInput!]
    NOT?: NexusGenInputs['CoursesWhereInput'][] | null; // [CoursesWhereInput!]
    OR?: NexusGenInputs['CoursesWhereInput'][] | null; // [CoursesWhereInput!]
    cancellations?: NexusGenInputs['CancellationsListRelationFilter'] | null; // CancellationsListRelationFilter
    children?: NexusGenInputs['ChildrenListRelationFilter'] | null; // ChildrenListRelationFilter
    day_of_week?: NexusGenInputs['IntFilter'] | null; // IntFilter
    end_time?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    places?: NexusGenInputs['IntFilter'] | null; // IntFilter
    start_time?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  DateTimeNullableFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeNullableFilter'] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  EnumRoleEnumFilter: { // input type
    equals?: NexusGenEnums['RoleEnum'] | null; // RoleEnum
    in?: NexusGenEnums['RoleEnum'][] | null; // [RoleEnum!]
    not?: NexusGenInputs['NestedEnumRoleEnumFilter'] | null; // NestedEnumRoleEnumFilter
    notIn?: NexusGenEnums['RoleEnum'][] | null; // [RoleEnum!]
  }
  EnumStatusEnumFilter: { // input type
    equals?: NexusGenEnums['StatusEnum'] | null; // StatusEnum
    in?: NexusGenEnums['StatusEnum'][] | null; // [StatusEnum!]
    not?: NexusGenInputs['NestedEnumStatusEnumFilter'] | null; // NestedEnumStatusEnumFilter
    notIn?: NexusGenEnums['StatusEnum'][] | null; // [StatusEnum!]
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedDateTimeNullableFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeNullableFilter'] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedEnumRoleEnumFilter: { // input type
    equals?: NexusGenEnums['RoleEnum'] | null; // RoleEnum
    in?: NexusGenEnums['RoleEnum'][] | null; // [RoleEnum!]
    not?: NexusGenInputs['NestedEnumRoleEnumFilter'] | null; // NestedEnumRoleEnumFilter
    notIn?: NexusGenEnums['RoleEnum'][] | null; // [RoleEnum!]
  }
  NestedEnumStatusEnumFilter: { // input type
    equals?: NexusGenEnums['StatusEnum'] | null; // StatusEnum
    in?: NexusGenEnums['StatusEnum'][] | null; // [StatusEnum!]
    not?: NexusGenInputs['NestedEnumStatusEnumFilter'] | null; // NestedEnumStatusEnumFilter
    notIn?: NexusGenEnums['StatusEnum'][] | null; // [StatusEnum!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  OptionsWhereInput: { // input type
    AND?: NexusGenInputs['OptionsWhereInput'][] | null; // [OptionsWhereInput!]
    NOT?: NexusGenInputs['OptionsWhereInput'][] | null; // [OptionsWhereInput!]
    OR?: NexusGenInputs['OptionsWhereInput'][] | null; // [OptionsWhereInput!]
    Prices?: NexusGenInputs['PricesListRelationFilter'] | null; // PricesListRelationFilter
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    orders?: NexusGenInputs['Options_setListRelationFilter'] | null; // Options_setListRelationFilter
  }
  Options_setListRelationFilter: { // input type
    every?: NexusGenInputs['Options_setWhereInput'] | null; // Options_setWhereInput
    none?: NexusGenInputs['Options_setWhereInput'] | null; // Options_setWhereInput
    some?: NexusGenInputs['Options_setWhereInput'] | null; // Options_setWhereInput
  }
  Options_setWhereInput: { // input type
    AND?: NexusGenInputs['Options_setWhereInput'][] | null; // [Options_setWhereInput!]
    NOT?: NexusGenInputs['Options_setWhereInput'][] | null; // [Options_setWhereInput!]
    OR?: NexusGenInputs['Options_setWhereInput'][] | null; // [Options_setWhereInput!]
    cancelled_at?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    option?: NexusGenInputs['OptionsWhereInput'] | null; // OptionsWhereInput
    options_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    order?: NexusGenInputs['OrdersWhereInput'] | null; // OrdersWhereInput
    orders_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    paid_at?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    price?: NexusGenInputs['PricesWhereInput'] | null; // PricesWhereInput
    prices_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    status?: NexusGenInputs['EnumStatusEnumFilter'] | null; // EnumStatusEnumFilter
  }
  OrdersListRelationFilter: { // input type
    every?: NexusGenInputs['OrdersWhereInput'] | null; // OrdersWhereInput
    none?: NexusGenInputs['OrdersWhereInput'] | null; // OrdersWhereInput
    some?: NexusGenInputs['OrdersWhereInput'] | null; // OrdersWhereInput
  }
  OrdersWhereInput: { // input type
    AND?: NexusGenInputs['OrdersWhereInput'][] | null; // [OrdersWhereInput!]
    NOT?: NexusGenInputs['OrdersWhereInput'][] | null; // [OrdersWhereInput!]
    OR?: NexusGenInputs['OrdersWhereInput'][] | null; // [OrdersWhereInput!]
    cancelled_at?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    options_set?: NexusGenInputs['Options_setListRelationFilter'] | null; // Options_setListRelationFilter
    users?: NexusGenInputs['UsersWhereInput'] | null; // UsersWhereInput
    users_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  PricesListRelationFilter: { // input type
    every?: NexusGenInputs['PricesWhereInput'] | null; // PricesWhereInput
    none?: NexusGenInputs['PricesWhereInput'] | null; // PricesWhereInput
    some?: NexusGenInputs['PricesWhereInput'] | null; // PricesWhereInput
  }
  PricesWhereInput: { // input type
    AND?: NexusGenInputs['PricesWhereInput'][] | null; // [PricesWhereInput!]
    NOT?: NexusGenInputs['PricesWhereInput'][] | null; // [PricesWhereInput!]
    OR?: NexusGenInputs['PricesWhereInput'][] | null; // [PricesWhereInput!]
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    option?: NexusGenInputs['OptionsWhereInput'] | null; // OptionsWhereInput
    options_id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    options_set?: NexusGenInputs['Options_setListRelationFilter'] | null; // Options_setListRelationFilter
    price?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  UsersOrderByInput: { // input type
    created_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    deleted_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    first_name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    password?: NexusGenEnums['SortOrder'] | null; // SortOrder
    phone_number?: NexusGenEnums['SortOrder'] | null; // SortOrder
    role?: NexusGenEnums['SortOrder'] | null; // SortOrder
    secondary_email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    verfifed_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UsersWhereInput: { // input type
    AND?: NexusGenInputs['UsersWhereInput'][] | null; // [UsersWhereInput!]
    NOT?: NexusGenInputs['UsersWhereInput'][] | null; // [UsersWhereInput!]
    OR?: NexusGenInputs['UsersWhereInput'][] | null; // [UsersWhereInput!]
    children?: NexusGenInputs['ChildrenListRelationFilter'] | null; // ChildrenListRelationFilter
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    deleted_at?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    first_name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    orders?: NexusGenInputs['OrdersListRelationFilter'] | null; // OrdersListRelationFilter
    password?: NexusGenInputs['StringFilter'] | null; // StringFilter
    phone_number?: NexusGenInputs['StringFilter'] | null; // StringFilter
    role?: NexusGenInputs['EnumRoleEnumFilter'] | null; // EnumRoleEnumFilter
    secondary_email?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    verfifed_at?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
  }
  UsersWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
  RoleEnum: "ADMIN" | "MONITOR" | "USER"
  SortOrder: "asc" | "desc"
  StatusEnum: "NOTAPPLICABLE" | "NOTYETPAYABLE" | "PAID" | "UNPAID"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  Date: any
  DateTime: any
}

export interface NexusGenObjects {
  Query: {};
  User: { // root type
    created_at?: NexusGenScalars['Date'] | null; // Date
    email?: string | null; // String
    first_name?: string | null; // String
    id?: number | null; // Int
    name?: string | null; // String
    password?: string | null; // String
    phone_number?: string | null; // String
    secondary_email?: string | null; // String
    vertified_at?: NexusGenScalars['Date'] | null; // Date
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Query: { // field return type
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  User: { // field return type
    created_at: NexusGenScalars['Date'] | null; // Date
    email: string | null; // String
    first_name: string | null; // String
    id: number | null; // Int
    name: string | null; // String
    password: string | null; // String
    phone_number: string | null; // String
    secondary_email: string | null; // String
    vertified_at: NexusGenScalars['Date'] | null; // Date
  }
}

export interface NexusGenFieldTypeNames {
  Query: { // field return type name
    users: 'User'
  }
  User: { // field return type name
    created_at: 'Date'
    email: 'String'
    first_name: 'String'
    id: 'Int'
    name: 'String'
    password: 'String'
    phone_number: 'String'
    secondary_email: 'String'
    vertified_at: 'Date'
  }
}

export interface NexusGenArgTypes {
  Query: {
    users: { // args
      after?: NexusGenInputs['UsersWhereUniqueInput'] | null; // UsersWhereUniqueInput
      before?: NexusGenInputs['UsersWhereUniqueInput'] | null; // UsersWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['UsersOrderByInput'][] | null; // [UsersOrderByInput!]
      where?: NexusGenInputs['UsersWhereInput'] | null; // UsersWhereInput
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: ContextModule;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}